version: '3.5'

services:
    nginx:
        image: nginx
        container_name: felichita-nginx
        ports:
            - '8082:80'
        volumes:
            - './.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
            - './:/code'

    web:
        container_name: felichita-web
        build:
            dockerfile: Dockerfile
            context: ./
        tty: true
        volumes:
            - './:/code'

    mysql:
        container_name: felichita-db
        image: mysql:8
        environment:
            MYSQL_DATABASE: felichita
            MYSQL_USER: user
            MYSQL_PASSWORD: Q1w2e3r4
            MYSQL_RANDOM_ROOT_PASSWORD: yes
        ports:
            - '3307:3306'
